[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "qubecalib"
dynamic = ["version"]
requires-python = ">=3.9"
authors = [{ name = "h403", email = "shiomi@ieee.org" }]
description = "QuBE calibration tools"
readme = "README.md"
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: GPL",
    "Programming Language :: Python :: 3",
]
dependencies = [
    "jupyter ~= 1.0",
    "numpy ~= 1.0",
    "matplotlib ~= 3.0",
    "plotly ~= 5.0",
    "tqdm ~= 4.0",
    "pyyaml ~= 6.0",
    "types-PyYAML == 6.0.*",
    "pytest",
    "pytest-mock",
    "PyGObject == 3.50.0",
    "aiocoap >= 0.4.7, < 0.4.16;python_version>='3.10'",
    "aiocoap == 0.4.7, ;python_version<'3.9'",
    "quel_ic_config==0.10.5",
]

[tool.setuptools.dynamic]
version = { attr = "qubecalib.__version__" }

[tool.pytest.ini_options]
# cf. https://docs.pytest.org/en/6.2.x/pythonpath.html#import-modes
addopts = "--import-mode=importlib"

[tool.mypy]
ignore_missing_imports = true
